package it.gov.pagopa.tests.testutil

import it.gov.pagopa.common.util.ConfigUtil.ConfigData
import it.gov.pagopa.config._

import java.time.OffsetDateTime

object TestDData {

  val baseCanale = Channel(
    TestItems.canale,
    Some(s"${TestItems.canale}_descr"),
    true,
    TestItems.canalePwd,
    Connection("HTTP", "localhost", 8087),
    TestItems.intPSP,
    None, //proxy
    Some(Service(Some("FespPsp"), Some("targetHost"), Some(8081), Some("targetPath"))),
    Some(Service(Some("servizioNMP"), Some("targetHostNMP"), Some(8082), Some("targetPathNMP"))),
    10,
    Timeouts(10, 10, 10),
    false,
    Redirect(Some("HTTP"), Some("redirectIp"), Some("redirectPath"), Some(8083), Some("redirectQS")),
    "ATTIVATO_PRESSO_PSP",
    Some("idPsp1"),
    true,
    false,
    true,
    true,
    true,
    2,
    false,
    false //Some(false)
  )
  val basePA = CreditorInstitution(TestItems.PA, true, Some("pa DEV ragsoc"), Some("pa DEV descr"), None, true, false, false)
  val basePSP = PaymentServiceProvider(TestItems.PSP, true, Some("CFpspTest"), Some("Test-PSP"), Some("ABIAA"), Some("bic"), Some("Test"), true, false, Some("tax"), Some("vat"))
  val baseStazione = Station(
    TestItems.stazione,
    true,
    2,
    Connection("HTTP", "localhost", 8087),
    Some(Connection("HTTP", "localhost", 8088)),
    TestItems.stazionePwd,
    Redirect(Some("HTTP"), Some("redirectIp"), Some("redirectPath"), Some(8083), Some("redirectQS")),
    Some(Service(Some("service"), Some("targetHost"), Some(8081), Some("targetPath"))),
    Some(Service(Some("servicePof"), Some("targetHostPof"), Some(8081), Some("targetPathPof"))),
    Some(Service(Some("serviceMod4"), None, None, None)),
    TestItems.testIntPA,
    None,
    10,
    Timeouts(10, 10, 10),
    true,
    1,
    false //Some(false)
  )

  val ddataMap: ConfigData = {
    ConfigDataV1(
      "version",
      Map(
        TestItems.PA -> basePA.copy(creditorInstitutionCode = TestItems.PA),
        "77777777777" -> basePA.copy(creditorInstitutionCode = "77777777777", true, description = Some("77777777777"), businessName = Some("77777777777")),
        TestItems.PA_FTP -> basePA.copy(creditorInstitutionCode = TestItems.PA_FTP, reportingFtp = true),
        TestItems.PA_old -> basePA.copy(creditorInstitutionCode = TestItems.PA_old),
        TestItems.PA_2 -> basePA.copy(creditorInstitutionCode = TestItems.PA_2),
        TestItems.PA_DISABLED -> basePA.copy(creditorInstitutionCode = TestItems.PA_DISABLED, enabled = false)
      ),
      Map(
        TestItems.testIntPA -> BrokerCreditorInstitution(TestItems.testIntPA, true, Some("INTPAT"), false),
        TestItems.testIntPA_DISABLED -> BrokerCreditorInstitution(TestItems.testIntPA_DISABLED, false, Some("INTPAT_dis"), false)),
      Map(
        TestItems.stazione -> baseStazione.copy(stationCode = TestItems.stazione, version = 2),
        TestItems.stazione_NO_INT -> baseStazione.copy(stationCode = TestItems.stazione_NO_INT, version = 2, brokerCode = "no"),
        TestItems.stazione_DISABLED -> baseStazione.copy(stationCode = TestItems.stazione_DISABLED, version = 2, enabled = false),
        TestItems.stazione_INT_DISABLED -> baseStazione.copy(stationCode = TestItems.stazione_INT_DISABLED, version = 2, brokerCode = TestItems.testIntPA_DISABLED),
        TestItems.stazioneOld -> baseStazione.copy(stationCode = TestItems.stazioneOld, version = 1),
        TestItems.stazioneNonIstantanea -> baseStazione.copy(stationCode = TestItems.stazioneNonIstantanea, version = 2, invioRtIstantaneo = false),
        TestItems.stazionePV2 -> baseStazione.copy(stationCode = TestItems.stazionePV2, version = 2, invioRtIstantaneo = false, primitiveVersion = 2),
        TestItems.stazionePV2Broadcast -> baseStazione.copy(stationCode = TestItems.stazionePV2Broadcast, version = 2, invioRtIstantaneo = false, primitiveVersion = 2)
      ),
      Map(
        TestItems.stazione -> StationCreditorInstitution(TestItems.PA, TestItems.stazione, Some(1), None, Some(0), false, false, 1, true),
        TestItems.stazione_NO_INT -> StationCreditorInstitution(TestItems.PA, TestItems.stazione_NO_INT, Some(9), None, Some(0), false, false, 1, true),
        TestItems.stazione_DISABLED -> StationCreditorInstitution(TestItems.PA, TestItems.stazione_DISABLED, Some(7), None, Some(0), false, false, 1, true),
        TestItems.stazione_INT_DISABLED -> StationCreditorInstitution(TestItems.PA, TestItems.stazione_INT_DISABLED, Some(8), None, Some(0), false, false, 1, true),
        TestItems.stazioneOld -> StationCreditorInstitution(TestItems.PA, TestItems.stazioneOld, Some(2), None, None, true, false, 1, false),
        "77777777777" -> StationCreditorInstitution("77777777777", TestItems.stazioneOld, Some(2), Some(1), Some(1), true, false, 1, false),
        TestItems.stazione + "ftp" -> StationCreditorInstitution(TestItems.PA_FTP, TestItems.stazioneOld, Some(2), Some(1), Some(1), true, false, 1, false),
        TestItems.paOldStazioneOld -> StationCreditorInstitution(TestItems.PA_old, TestItems.stazioneOld, Some(2), Some(1), None, true, false, 1, false),
        TestItems.stazioneNonIstantanea -> StationCreditorInstitution(TestItems.PA, TestItems.stazioneNonIstantanea, Some(2), Some(1), Some(1), false, false, 1, true),
        TestItems.stazionePV2 -> StationCreditorInstitution(TestItems.PA, TestItems.stazionePV2, Some(3), Some(1), Some(1), false, false, 2, true),
        TestItems.stazionePV2Broadcast -> StationCreditorInstitution(TestItems.PA, TestItems.stazionePV2Broadcast, Some(4), Some(1), Some(1), false, true, 2, true),
        TestItems.PA_2 + TestItems.stazioneNonIstantanea -> StationCreditorInstitution(TestItems.PA_2, TestItems.stazioneNonIstantanea, Some(5), Some(1), Some(1), false, true, 1, true)
      ),
      Map("QR-CODE" -> Encoding("QR-CODE", "QR-CODE"), "BARCODE-128-AIM" -> Encoding("BARCODE-128-AIM", "BARCODE-128-AIM")),
      Map(
        TestItems.PA -> CreditorInstitutionEncoding("QR-CODE", TestItems.PA + "0", TestItems.PA),
        TestItems.PA + "1" -> CreditorInstitutionEncoding("BARCODE-128-AIM", TestItems.PA + "1", TestItems.PA)
      ),
      Map(
        s"${TestItems.PA}-IT96R0123454321000000012345" -> Iban("IT96R0123454321000000012345", TestItems.PA, OffsetDateTime.now(), OffsetDateTime.now(), None, None, None, None),
        s"77777777777-IT96R0123454321000000012345" -> Iban("IT96R0123454321000000012345", "77777777777", OffsetDateTime.now(), OffsetDateTime.now(), None, None, None, None),
        s"${TestItems.PA}-IT96R0760154321123456789001" -> Iban("IT96R0760154321123456789001", TestItems.PA, OffsetDateTime.now(), OffsetDateTime.now(), None, None, None, None),
        s"${TestItems.PA_2}-IT96R0123454321000000012345" -> Iban("IT96R0123454321000000012345", TestItems.PA_2, OffsetDateTime.now(), OffsetDateTime.now(), None, None, None, None)
      ),
      Map(TestItems.PA -> CreditorInstitutionInformation("")),
      Map(
        TestItems.PSP -> basePSP.copy(pspCode = TestItems.PSP, taxCode = Some(TestItems.PSP)),
        TestItems.PSP_NO_BOLLO -> basePSP.copy(pspCode = TestItems.PSP_NO_BOLLO, taxCode = Some(TestItems.PSP_NO_BOLLO), digitalStamp = false),
        "70000000001" -> basePSP.copy(pspCode = "70000000001", taxCode = Some("70000000001")),
        "idPsp1" -> basePSP.copy(pspCode = "idPsp1", taxCode = Some("idPsp1")),
        TestItems.PSPMod3New -> basePSP.copy(pspCode = TestItems.PSPMod3New, taxCode = Some(TestItems.PSPMod3New)),
        TestItems.PSPAgid -> basePSP.copy(pspCode = TestItems.PSPAgid, taxCode = Some(TestItems.PSPAgid)),
        TestItems.PSPECOMMERCE -> basePSP.copy(pspCode = TestItems.PSPECOMMERCE, taxCode = Some(TestItems.PSPECOMMERCE)),
        TestItems.PSP_DISABLED -> basePSP.copy(pspCode = TestItems.PSP_DISABLED, taxCode = Some(TestItems.PSP_DISABLED), enabled = false)
      ),
      Map(
        TestItems.intPSP -> BrokerPsp(TestItems.intPSP, Some("INTPSPT"), true, true),
        TestItems.intPSP_DISABLED -> BrokerPsp(TestItems.intPSP_DISABLED, Some("intPSP_DISABLED"), false, true),
        TestItems.intPSPMod3New -> BrokerPsp(TestItems.intPSPMod3New, Some(TestItems.intPSPMod3New), true, true),
        TestItems.intPSPAgid -> BrokerPsp(TestItems.intPSPAgid, Some(TestItems.intPSPAgid), true, true)
      ),
      Map(
        "AD" -> PaymentType("AD", Some("Addebito diretto")),
        "BBT" -> PaymentType("BBT", Some("Bonifico bancario telematico")),
        "BP" -> PaymentType("BP", Some("Bollettino postale")),
        "CP" -> PaymentType("CP", Some("Carta di pagamento")),
        "OBEP" -> PaymentType("OBEP", Some("Online Banking Electronic Payment")),
        "PO" -> PaymentType("PO", Some("Pagamento attivato presso PSP")),
        "JIF" -> PaymentType("JIF", Some("Jiffy")),
        "MYBK" -> PaymentType("MYBK", Some("MyBank")),
        "PPAL" -> PaymentType("PPAL", Some("PayPal")),
        "BPAY" -> PaymentType("BPAY", Some("Bancomat Pay")),
        "NODOPAY" -> PaymentType("NODOPAY", Some("Nodo Pay"))
      ),
      Map(
        "1" -> PspChannelPaymentType(TestItems.PSP, TestItems.canale, "PO"),
        "2" -> PspChannelPaymentType(TestItems.PSP, TestItems.canale, "CP"),
        "3" -> PspChannelPaymentType(TestItems.PSP, TestItems.canaleImmediato, "CP"),
        "4" -> PspChannelPaymentType(TestItems.PSP, TestItems.canaleImmediato, "PO"),
        "5" -> PspChannelPaymentType(TestItems.PSP, TestItems.canaleDifferito, "MYBK"),
        "6" -> PspChannelPaymentType(TestItems.PSP, TestItems.canaleDifferito, "PO"),
        "7" -> PspChannelPaymentType(TestItems.PSPMod3New, TestItems.canaleAgid, "PO"),
        "8" -> PspChannelPaymentType(TestItems.PSPMod3New, TestItems.canaleMod3new, "PO"),
        "9" -> PspChannelPaymentType(TestItems.PSPAgid, TestItems.canaleAgid, "PO"),
        "10" -> PspChannelPaymentType(TestItems.PSPAgid, TestItems.canaleAgid, "CP"),
        "11" -> PspChannelPaymentType(TestItems.PSP, TestItems.canalePayPal, "PPAL"),
        "12" -> PspChannelPaymentType(TestItems.PSP, TestItems.canalePull, "PO"),
        "13" -> PspChannelPaymentType(TestItems.PSP, TestItems.canaleIrr, "PO"),
        "14" -> PspChannelPaymentType(TestItems.PSPAgid, TestItems.canaleCD, "PO"),
        "15" -> PspChannelPaymentType(TestItems.PSP, TestItems.canaleBPay, "BPAY"),
        "16" -> PspChannelPaymentType(TestItems.PSP, TestItems.canaleBPayWrongModello, "BPAY"),
        "17" -> PspChannelPaymentType(TestItems.PSP, TestItems.canaleNodoPay, "NODOPAY"),
        "18" -> PspChannelPaymentType(TestItems.PSP, TestItems.canaleNodoPayWrongModello, "NODOPAY"),
        "19" -> PspChannelPaymentType(TestItems.PSP, TestItems.canaleNodoPayV1, "NODOPAY"),
        "20" -> PspChannelPaymentType(TestItems.PSPECOMMERCE, TestItems.canale, "PO"),
        "21" -> PspChannelPaymentType(TestItems.PSPECOMMERCE, TestItems.canaleNodoPay, "NODOPAY"),
        "22" -> PspChannelPaymentType(TestItems.PSP, TestItems.canale, "AD"),
        "23" -> PspChannelPaymentType(TestItems.PSP, TestItems.canale, "OBEP"),
        "24" -> PspChannelPaymentType(TestItems.PSP_NO_BOLLO, TestItems.canale, "CP"),
        "25" -> PspChannelPaymentType(TestItems.PSP, TestItems.canaleImmediatoNoPlugin, "CP"),
      ),
      Map(
        "test2" -> Plugin("test2", None, None, None, None),
        "wpl02" -> Plugin("wpl02", None, None, None, None),
        "idPsp1" -> Plugin("idPsp1", None, None, None, None),
        "wpl04" -> Plugin("wpl04", None, None, None, None),
        "wpl06" -> Plugin("wpl06", None, None, None, None),
        "wpl05" -> Plugin("wpl05", None, None, None, None),
        "wpl03" -> Plugin("wpl03", None, None, None, None),
        "wpl07" -> Plugin("wpl07", None, None, None, None)
      ),
      Map(TestItems.PSP -> PspInformation("<xml></xml>")),
      Map(),
      Map(
        TestItems.canale -> baseCanale.copy(channelCode = TestItems.canale, paymentModel = "ATTIVATO_PRESSO_PSP"),
        TestItems.canale_DISABLED -> baseCanale.copy(channelCode = TestItems.canale_DISABLED, paymentModel = "ATTIVATO_PRESSO_PSP", enabled = false),
        TestItems.canaleImmediato -> baseCanale.copy(channelCode = TestItems.canaleImmediato, paymentModel = "IMMEDIATO"),
        TestItems.canaleImmediatoNoPlugin -> baseCanale.copy(channelCode = TestItems.canaleImmediatoNoPlugin, paymentModel = "IMMEDIATO", servPlugin = Some("AAA")),
        TestItems.canaleAgid -> baseCanale.copy(channelCode = TestItems.canaleAgid, brokerPspCode = TestItems.intPSPAgid, paymentModel = "IMMEDIATO_MULTIBENEFICIARIO"),
        TestItems.canaleMod3new -> baseCanale.copy(channelCode = TestItems.canaleMod3new, brokerPspCode = TestItems.intPSPMod3New, paymentModel = "IMMEDIATO"),
        TestItems.canaleDifferito -> baseCanale.copy(channelCode = TestItems.canaleDifferito, paymentModel = "DIFFERITO"),
        TestItems.canalePayPal -> baseCanale.copy(channelCode = TestItems.canalePayPal, paymentModel = "IMMEDIATO"),
        TestItems.canalePull -> baseCanale.copy(channelCode = TestItems.canalePull, paymentModel = "IMMEDIATO"),
        TestItems.canaleIrr -> baseCanale.copy(channelCode = TestItems.canaleIrr, paymentModel = "IMMEDIATO", connection = baseCanale.connection.copy(ip = "1.1.1.1")),
        TestItems.canaleCD -> baseCanale.copy(channelCode = TestItems.canaleCD, brokerPspCode = TestItems.intPSPCD, paymentModel = "ATTIVATO_PRESSO_PSP", connection = baseCanale.connection.copy(ip = "1.1.1.1")),
        TestItems.canaleBPay -> baseCanale.copy(channelCode = TestItems.canaleBPay, paymentModel = "IMMEDIATO"),
        TestItems.canaleBPayWrongModello -> baseCanale.copy(channelCode = TestItems.canaleBPayWrongModello, paymentModel = "ATTIVATO_PRESSO_PSP"),
        TestItems.canaleNodoPay -> baseCanale.copy(channelCode = TestItems.canaleNodoPay, paymentModel = "IMMEDIATO", primitiveVersion = 2),
        TestItems.canaleNodoPayWrongModello -> baseCanale.copy(channelCode = TestItems.canaleNodoPayWrongModello, paymentModel = "ATTIVATO_PRESSO_PSP"),
        TestItems.canaleNodoPayV1 -> baseCanale.copy(channelCode = TestItems.canaleNodoPayV1, paymentModel = "IMMEDIATO", primitiveVersion = 1)
      ),
      Map(
        "1" -> CdsService("00001", "tassa auto v1", "TassaAutomobilistica_1_1_0.xsd", 1, "Tassa automobilistica"),
        "2" -> CdsService("00002", "servizio2 v2", "TassaAutomobilistica_1_1_0.xsd", 2, "Altro"),
        "3" -> CdsService("00003", "servizio3 v2", "TassaAutomobilistica_1_1_0.xsd", 1, "Altro")
      ),
      Map(TestItems.PA -> CdsSubject(TestItems.PA, s"${TestItems.PA}descr"), TestItems.PAUnknown -> CdsSubject(TestItems.PAUnknown, s"${TestItems.PAUnknown}descr")),
      Map(
        "1-1" -> CdsSubjectService(TestItems.PA, "00001", "00001", OffsetDateTime.now().minusDays(1), Some(OffsetDateTime.now().plusDays(1)), true, Some(TestItems.stazione), None),
        "1-2" -> CdsSubjectService(TestItems.PA, "00002", "00002", OffsetDateTime.now().minusDays(2), Some(OffsetDateTime.now().plusDays(2)), true, Some(TestItems.stazione), None),
        "1-3" -> CdsSubjectService(TestItems.PA, "00002", "00003", OffsetDateTime.now().minusDays(3), Some(OffsetDateTime.now().plusDays(3)), false, Some(TestItems.stazione), None),
        "1-4" -> CdsSubjectService(TestItems.PA, "00003", "00004", OffsetDateTime.now().minusDays(4), Some(OffsetDateTime.now().plusDays(4)), false, Some(TestItems.stazione), None),
        "1-5" -> CdsSubjectService(TestItems.PAUnknown, "00002", "00005", OffsetDateTime.now().minusDays(5), Some(OffsetDateTime.now().plusDays(5)), false, Some(TestItems.stazione), None),
        "1-6" -> CdsSubjectService(TestItems.PAUnknown, "00001", "00006", OffsetDateTime.now().minusDays(6), Some(OffsetDateTime.now().plusDays(6)), false, Some(TestItems.stazione), None)
      ),
      Map("Altro" -> CdsCategory("Altro"), "Tassa automobilistica" -> CdsCategory("Tassa automobilistica"), "Donazioni" -> CdsCategory("Donazioni")),
      Map(
        "GLOBAL-azureSdkClientReEventEnabled" -> ConfigurationKey("", "", "false", None),
        "GLOBAL-ccpRandomTraduttore" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-chiediSceltaWisp.tipoVersamento" -> ConfigurationKey("", "", "BBT", None),
        "GLOBAL-default_durata_estensione_token_IO" -> ConfigurationKey("", "", "10", None),
        "GLOBAL-default_durata_token_IO" -> ConfigurationKey("", "", "15000", None),
        "GLOBAL-default_idempotency_key_validity_minutes" -> ConfigurationKey("", "", "10", None),
        "GLOBAL-default_token_duration_validity_millis" -> ConfigurationKey("", "", "10000", None),
        "GLOBAL-flag.chiediInfoPagamento.useNewField" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-ftp.env.path" -> ConfigurationKey("", "", "pate_", None),
        "GLOBAL-httpmethod.wfesp.pa2wfesp" -> ConfigurationKey("", "", "get", None),
        "GLOBAL-httpmethod.wfesp.psp2wfesp" -> ConfigurationKey("", "", "esito", None),
        "GLOBAL-httpmethod.wfesp.psp2wfespMS" -> ConfigurationKey("", "", "esitoMS", None),
        "GLOBAL-idCanaleAGID" -> ConfigurationKey("", "", TestItems.canaleAgid, None),
        "GLOBAL-idCanaleCD" -> ConfigurationKey("", "", TestItems.canaleCD, None),
        "GLOBAL-idCanaleMod3New" -> ConfigurationKey("", "", TestItems.canaleMod3new, None),
        "GLOBAL-idempotency.activate.ko.duration.days" -> ConfigurationKey("", "", "1", None),
        "GLOBAL-idempotency.outcome.ko.duration.days" -> ConfigurationKey("", "", "1", None),
        "GLOBAL-idempotency.outcome.ok.duration.days" -> ConfigurationKey("", "", "1", None),
        "GLOBAL-idIntPspMod3New" -> ConfigurationKey("", "", TestItems.intPSPMod3New, None),
        "GLOBAL-idPlugin.mybank" -> ConfigurationKey("", "", "wpl04", None),
        "GLOBAL-idPspAGID" -> ConfigurationKey("", "", TestItems.PSPAgid, None),
        "GLOBAL-idPspCD" -> ConfigurationKey("", "", TestItems.PSPCD, None),
        "GLOBAL-idPspMod3New" -> ConfigurationKey("", "", TestItems.PSPMod3New, None),
        "GLOBAL-id_psp_poste" -> ConfigurationKey("", "", "POSTE", None),
        "GLOBAL-intPspAGID" -> ConfigurationKey("", "", TestItems.intPSPAgid, None),
        "GLOBAL-intPspCD" -> ConfigurationKey("", "", TestItems.intPSPCD, None),
        "GLOBAL-inviaCarrelloRpt.maxNumRptInCartMultibeneficiario" -> ConfigurationKey("", "", "2", None),
        "GLOBAL-inviaCarrelloRpt.maxVersamentiInSecondRptMultibeneficiario" -> ConfigurationKey("", "", "1", None),
        "GLOBAL-istitutoAttestante.capAttestante" -> ConfigurationKey("", "", "00144", None),
        "GLOBAL-istitutoAttestante.civicoAttestante" -> ConfigurationKey("", "", "21", None),
        "GLOBAL-istitutoAttestante.codiceUnitOperAttestante" -> ConfigurationKey("", "", "n/a", None),
        "GLOBAL-istitutoAttestante.denominazioneAttestante" -> ConfigurationKey("", "", "Agenzia per l'Italia Digitale", None),
        "GLOBAL-istitutoAttestante.denomUnitOperAttestante" -> ConfigurationKey("", "", "n/a", None),
        "GLOBAL-istitutoAttestante.identificativoUnivocoAttestante.codiceIdentificativoUnivoco" -> ConfigurationKey("", "", "97735020584", None),
        "GLOBAL-istitutoAttestante.identificativoUnivocoAttestante.tipoIdentificativoUnivoco" -> ConfigurationKey("", "", "G", None),
        "GLOBAL-istitutoAttestante.indirizzoAttestante" -> ConfigurationKey("", "", "Via Liszt", None),
        "GLOBAL-istitutoAttestante.localitaAttestante" -> ConfigurationKey("", "", "Roma", None),
        "GLOBAL-istitutoAttestante.nazioneAttestante" -> ConfigurationKey("", "", "IT", None),
        "GLOBAL-istitutoAttestante.provinciaAttestante" -> ConfigurationKey("", "", "RM", None),
        "GLOBAL-mod3_descoping" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-mod3_inizio" -> ConfigurationKey("", "", "2021-01-01", None),
        "GLOBAL-mybank.params.passaggioCodiceMyBank" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-outcome_retry_active" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-paymentmanager.baseurl" -> ConfigurationKey("", "", "http://localhost:8080", None),
        "GLOBAL-scheduler.annullamentoRptMaiRichiesteDaPmPollerMinutesToBack" -> ConfigurationKey("", "", "0", None),
        "GLOBAL-scheduler.cancelIOPaymentActorMinutesToBack" -> ConfigurationKey("", "", "0", None),
        "GLOBAL-scheduler.ftpUploadRetryPollerMaxRetry" -> ConfigurationKey("", "", "5", None),
        "GLOBAL-scheduler.jobName_annullamentoRptMaiRichiesteDaPm.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_annullamentoRptMaiRichiesteDaPm.jobDescription" -> ConfigurationKey("", "", "Description", None),
        "GLOBAL-scheduler.jobName_ftpUpload.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_ftpUpload.jobDescription" -> ConfigurationKey("", "", "Description", None),
        "GLOBAL-scheduler.jobName_generaRendicontazioneBollo.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_generaRendicontazioneBollo.jobDescription" -> ConfigurationKey("", "", "Description", None),
        "GLOBAL-scheduler.jobName_mod3CancelV2.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_mod3CancelV1.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_positionRetrySendPaymentResult.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_mod3GenerateReceipt.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_mod3Riconciliazione.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_mod3UpdateNotifiedPositionPayment.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_paInviaRt.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_paInviaRtRecovery.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_paInviaRt.jobDescription" -> ConfigurationKey("", "", "Description", None),
        "GLOBAL-scheduler.jobName_paRetryPaInviaRtNegative.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_paRetryPaInviaRtNegative.jobDescription" -> ConfigurationKey("", "", "Description", None),
        "GLOBAL-scheduler.jobName_paSendRt.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_pspChiediAvanzamentoRpt.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_pspChiediAvanzamentoRpt.jobDescription" -> ConfigurationKey("", "", "Description", None),
        "GLOBAL-scheduler.jobName_pspChiediListaAndChiediRt.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_pspChiediListaAndChiediRt.jobDescription" -> ConfigurationKey("", "", "Description", None),
        "GLOBAL-scheduler.jobName_pspNotificaCancellazione.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_pspNotificaCancellazione.jobDescription" -> ConfigurationKey("", "", "Description", None),
        "GLOBAL-scheduler.jobName_pspRetryAckNegative.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_pspRetryAckNegative.jobDescription" -> ConfigurationKey("", "", "Description", None),
        "GLOBAL-scheduler.jobName_pspRetryNotificheCancellazioneRpt.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_pspRetryNotificheCancellazioneRpt.jobDescription" -> ConfigurationKey("", "", "Description", None),
        "GLOBAL-scheduler.jobName_pspSendPayment.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_refreshConfiguration.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_refreshConfiguration.jobDescription" -> ConfigurationKey("", "", "60", None),
        "GLOBAL-scheduler.jobName_retryPspSendPayment.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_rtPullRecoveryPush.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_rtPullRecoveryPush.jobDescription" -> ConfigurationKey("", "", "Description", None),
        "GLOBAL-scheduler.jobName_idempotencyCacheClean.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_idempotencyCacheClean.jobDescription" -> ConfigurationKey("", "", "Description", None),
        "GLOBAL-scheduler.jobName_paRetryAttivaRpt.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-scheduler.jobName_paRetryAttivaRpt.jobDescription" -> ConfigurationKey("", "", "Description", None),
        "GLOBAL-scheduler.mod3Cancel.minutesWaitPaOld" -> ConfigurationKey("", "", "0", None),
        "GLOBAL-scheduler.paAttivaRptMaxRetry" -> ConfigurationKey("", "", "5", None),
        "GLOBAL-scheduler.paRetryPaInviaRtNegativePollerMaxRetry" -> ConfigurationKey("", "", "4", None),
        "GLOBAL-scheduler.paSendRtMaxRetry" -> ConfigurationKey("", "", "5", None),
        "GLOBAL-scheduler.pspChiediAvanzamentoRptPollerMaxRetry" -> ConfigurationKey("", "", "6", None),
        "GLOBAL-scheduler.pspRetryAckNegativePollerMaxRetry" -> ConfigurationKey("", "", "3", None),
        "GLOBAL-scheduler.pspRetryNotificheCancellazioneRptPollerMaxRetry" -> ConfigurationKey("", "", "3", None),
        "GLOBAL-scheduler.retryPspSendPayment" -> ConfigurationKey("", "", "5", None),
        "GLOBAL-scheduler.rptExpiringDays" -> ConfigurationKey("", "", "8", None),
        "GLOBAL-scheduler.suspendAllJobs" -> ConfigurationKey("", "", "false", None),
        "GLOBAL-scheduler.sendPaymentResultPollerMaxRetry" -> ConfigurationKey("", "", "5", None),
        "GLOBAL-scheduler.sendPaymentResultPollerMinutesBack" -> ConfigurationKey("", "", "0", None),
        "GLOBAL-timeout.paSendRTV2" -> ConfigurationKey("", "", "TIMEOUT_A", None),
        "GLOBAL-timeout.pspNotifyPaymentV2" -> ConfigurationKey("", "", "TIMEOUT_A", None),
        "GLOBAL-timeout.paGetPaymentV2" -> ConfigurationKey("", "", "TIMEOUT_A", None),
        "GLOBAL-timeout.cdInfoWisp" -> ConfigurationKey("", "", "TIMEOUT_A", None),
        "GLOBAL-timeoutForSingleProcessSeconds" -> ConfigurationKey("", "", "130", None),
        "GLOBAL-timeout.paaAttivaRPT" -> ConfigurationKey("", "", "TIMEOUT_A", None),
        "GLOBAL-timeout.pspNotifyPayment" -> ConfigurationKey("", "", "TIMEOUT_A", None),
        "GLOBAL-timeout.paaChiediNumeroAvviso" -> ConfigurationKey("", "", "TIMEOUT_A", None),
        "GLOBAL-timeout.paActivatePaymentNoticeReq" -> ConfigurationKey("", "", "TIMEOUT_C", None),
        "GLOBAL-timeout.paaInviaRT.pull" -> ConfigurationKey("", "", "TIMEOUT_C", None),
        "GLOBAL-timeout.paaInviaRT.push" -> ConfigurationKey("", "", "TIMEOUT_B", None),
        "GLOBAL-timeout.paaVerificaRPT" -> ConfigurationKey("", "", "TIMEOUT_A", None),
        "GLOBAL-timeout.paGetPayment" -> ConfigurationKey("", "", "10", None),
        "GLOBAL-timeout.paGetPaymentReq" -> ConfigurationKey("", "", "TIMEOUT_C", None),
        "GLOBAL-timeout.paSendRT" -> ConfigurationKey("", "", "10", None),
        "GLOBAL-timeout.paVerifyPaymentNotice" -> ConfigurationKey("", "", "10", None),
        "GLOBAL-timeout.paVerifyPaymentNoticeReq" -> ConfigurationKey("", "", "TIMEOUT_C", None),
        "GLOBAL-timeout.pspChiediAvanzamentoRPT" -> ConfigurationKey("", "", "TIMEOUT_B", None),
        "GLOBAL-timeout.pspChiediListaRT" -> ConfigurationKey("", "", "TIMEOUT_C", None),
        "GLOBAL-timeout.pspChiediRT" -> ConfigurationKey("", "", "TIMEOUT_C", None),
        "GLOBAL-timeout.pspInviaAckRT" -> ConfigurationKey("", "", "TIMEOUT_C", None),
        "GLOBAL-timeout.pspInviaCarrelloRPTCarte" -> ConfigurationKey("", "", "TIMEOUT_B", None),
        "GLOBAL-timeout.pspInviaCarrelloRPT" -> ConfigurationKey("", "", "TIMEOUT_B", None),
        "GLOBAL-timeout.pspInviaRPT" -> ConfigurationKey("", "", "TIMEOUT_B", None),
        "GLOBAL-timeout.pspNotificaCancellazioneRPT" -> ConfigurationKey("", "", "TIMEOUT_C", None),
        "GLOBAL-timeout.pspSendPayment" -> ConfigurationKey("", "", "TIMEOUT_C", None),
        "GLOBAL-timeout.retryPspSendPayment" -> ConfigurationKey("", "", "TIMEOUT_C", None),
        "GLOBAL-timeout.paDemandPaymentNoticeRequest" -> ConfigurationKey("", "", "TIMEOUT_C", None),
        "GLOBAL-uri.wallet" -> ConfigurationKey("", "", "https://acardste.vaservices.eu:1443/wallet/welcome", None),
        "GLOBAL-uri.wfesp" -> ConfigurationKey("", "", "http://wfespxl.te.sia.eu/redirect", None),
        "GLOBAL-urlFittizioRedirectEC" -> ConfigurationKey("", "", "http://url.fittiz.io", None),
        "GLOBAL-useIdempotency" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-validate_input" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-validate_output" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-verificabollettino.validity.minutes" -> ConfigurationKey("", "", "10", None),
        "GLOBAL-wisp.timeoutScelta" -> ConfigurationKey("", "", "75", None),
        "GLOBAL-closePaymentV2DenyListTipoVersamento" -> ConfigurationKey("", "", "AD,BBT,BP,OBEP,PO,JIF,MYBK,BPAY,PPAL", None),
        "GLOBAL-sendBizEventsToEventHub" -> ConfigurationKey("", "", "false", None),
        "info-quadr-commissioneCaricoPa.invio.mail" -> ConfigurationKey("", "", "true", None),
        "info-quadr-commissioneCaricoPa.noData.message" -> ConfigurationKey("", "", "Nessun dato disponibile per il mese di riferimento", None),
        "info-quadr-commissioneCaricoPa.pdf.aggregato.footer" -> ConfigurationKey("", "", "", None),
        "info-quadr-commissioneCaricoPa.pdf.aggregato.header" -> ConfigurationKey("", "", "Tabella aggregato versamenti", None),
        "info-quadr-commissioneCaricoPa.pdf.dettaglio.footer" -> ConfigurationKey("", "", "", None),
        "info-quadr-commissioneCaricoPa.pdf.dettaglio.header" -> ConfigurationKey("", "", "Tabella dettaglio versamenti", None),
        "info-quadr-commissioneCaricoPa.template.sender.address.mail" -> ConfigurationKey("", "", "prova@prova.com", None),
        "info-quadr-commissioneCaricoPa.template.sender.name.mail" -> ConfigurationKey("", "", "PPT", None),
        "info-quadr-commissioneCaricoPa.template.subject.mail" -> ConfigurationKey("", "", "Report commissioniCaricoPa", None),
        "info-quadr-commissioneCaricoPsp.invio.mail" -> ConfigurationKey("", "", "true", None),
        "info-quadr-commissioneCaricoPsp.noData.message" -> ConfigurationKey("", "", "Nessun dato disponibile per il mese di riferimento", None),
        "info-quadr-commissioneCaricoPsp.pdf.aggregato.footer" -> ConfigurationKey("", "", "", None),
        "info-quadr-commissioneCaricoPsp.pdf.aggregato.header" -> ConfigurationKey("", "", "Tabella aggregato versamenti", None),
        "info-quadr-commissioneCaricoPsp.pdf.dettaglio.footer" -> ConfigurationKey("", "", "", None),
        "info-quadr-commissioneCaricoPsp.pdf.dettaglio.header" -> ConfigurationKey("", "", "Tabella dettaglio versamenti", None),
        "info-quadr-commissioneCaricoPsp.template.sender.address.mail" -> ConfigurationKey("", "", "prova@prova.com", None),
        "info-quadr-commissioneCaricoPsp.template.sender.name.mail" -> ConfigurationKey("", "", "PPT", None),
        "info-quadr-commissioneCaricoPsp.template.subject.mail" -> ConfigurationKey("", "", "Report commissioniCaricoPsp", None),
        "info-quadr-smtp.host" -> ConfigurationKey("", "", "10.10.39.132", None),
        "info-quadr-smtp.password" -> ConfigurationKey("", "", "pda", None),
        "info-quadr-smtp.port" -> ConfigurationKey("", "", "1026", None),
        "info-quadr-smtp.test.sia" -> ConfigurationKey("", "", "true", None),
        "info-quadr-smtp.username" -> ConfigurationKey("", "", "pda@dev.test", None),
        "info-quadr-versioneQuadrature" -> ConfigurationKey("", "", "6.1", None),
        "info-wisp-chiediListaPSP.ibanPosteMatch" -> ConfigurationKey("", "", "07601", None),
        "info-wisp-chiediListaPSP.listaIdPoste" -> ConfigurationKey("", "", "POSTE1", None),
        "info-wisp-chiediListaPSP.outputJsonValid" -> ConfigurationKey("", "", "true", None),
        "rendicontazioni-bollo.codiceIdentificativo.1" -> ConfigurationKey("", "", "SIA", None),
        "rendicontazioni-bollo.codiceIdentificativo.2" -> ConfigurationKey("", "", "YY", None),
        "rendicontazioni-bollo.dateFormat" -> ConfigurationKey("", "", "yyyy-MM-dd", None),
        "rendicontazioni-bollo.intermediario.CAPDelDomicilioFiscale" -> ConfigurationKey("", "", "20147", None),
        "rendicontazioni-bollo.intermediario.comuneDomicilioFiscale" -> ConfigurationKey("", "", "Milano", None),
        "rendicontazioni-bollo.intermediario.denominazione" -> ConfigurationKey("", "", "SIA S.p.A.", None),
        "rendicontazioni-bollo.intermediario.indirizzoFrazioneViaENumeroCivicoDelDomicilioFiscale" -> ConfigurationKey("", "", "Via Gonin, 36", None),
        "rendicontazioni-bollo.intermediario.siglaDellaProvinciaDelDomicilioFiscale" -> ConfigurationKey("", "", "MI", None),
        "rendicontazioni-bollo.mittente.codiceFiscale" -> ConfigurationKey("", "", "15376371009", None),
        "rendicontazioni-chiediElencoFlussiRendicontazioneDayLimit" -> ConfigurationKey("", "", "30", None),
        "rendicontazioni-ftp.internalFTPComponentEndpointHost" -> ConfigurationKey("", "", "0.0.0.0", None),
        "rendicontazioni-ftp.internalFTPComponentEndpointPort" -> ConfigurationKey("", "", "9610", None),
        "rpt-annulla-algoritmoFirmaRT" -> ConfigurationKey("", "", "SHA256withRSA", None),
        "rpt-info-chiediInfoPagamento.outputJsonValid" -> ConfigurationKey("", "", "true", None),
        "rpt-invia-inviaCarrelloRpt.maxNumRptInCart" -> ConfigurationKey("", "", "5", None),
        "rpt-invia-mybank.params.passaggioCodiceMyBank" -> ConfigurationKey("", "", "true", None),
        "rpt-invia-patch.ministeroDiGiustizia.active" -> ConfigurationKey("", "", "true", None),
        "rpt-invia-patch.ministeroDiGiustizia.idDominio" -> ConfigurationKey("", "", "01386030488", None),
        "rpt-modello4-aciDescrizione" -> ConfigurationKey("", "", "Automobile Club d'Italia", None),
        "rpt-modello4-aciId" -> ConfigurationKey("", "", "00493410583", None),
        "rpt-modello4-dataInizioValiditaBolloAuto" -> ConfigurationKey("", "", "2017-04-30T00:00:00", None),
        "rpt-modello4-descrizioneServizioBolloAuto" -> ConfigurationKey("", "", "Tassa automobilistica", None),
        "rpt-modello4-idServizioBolloAuto" -> ConfigurationKey("", "", "00001", None),
        "rpt-modello4-xsdRiferimentoBolloAuto" -> ConfigurationKey("", "", "TassaAutomobilistica_1_1_0.xsd", None),
        "rt-invia-idFaultBean.nodo" -> ConfigurationKey("", "", "NodoDeiPagamentiSPC", None),
        "GLOBAL-gec.enabled" -> ConfigurationKey("", "", "true", None),
        "GLOBAL-gec.fees.maxRetry" -> ConfigurationKey("", "", "0", None),
        "GLOBAL-gec.fees.maxOccurences" -> ConfigurationKey("", "", "10", None),
        "GLOBAL-idPspCheckout" -> ConfigurationKey("", "", TestItems.PSPCHECKOUT, None),
        "GLOBAL-idCanaleCheckout" -> ConfigurationKey("", "", TestItems.canaleCHECKOUT, None),
        "GLOBAL-idPspECommerce" -> ConfigurationKey("", "", TestItems.PSPECOMMERCE, None),
        "GLOBAL-idCanaleECommerce" -> ConfigurationKey("", "", TestItems.canaleECOMMERCE, None),
        "info-wisp-chiediListaPSP.listaPspLisPay" -> ConfigurationKey("", "", "lispay", None),
        "info-wisp-chiediListaPSP.listaCanaliLisPay" -> ConfigurationKey("", "", "lispay_1", None),
        "GLOBAL-parkedList_maxOccur" -> ConfigurationKey("", "", "100", None),
        "GLOBAL-parkedList_pollerLimitHours" -> ConfigurationKey("", "", "1", None),
        "GLOBAL-parkedList_pollerMinutesToBack" -> ConfigurationKey("", "", "0", None),
        "GLOBAL-invioReceiptStandin" -> ConfigurationKey("", "", "false", None)

      ),
      Map(),
      Map(),
      Map(
        "INVIAFLUSSORENDI_REQ" -> GdeConfiguration("INVIAFLUSSORENDI", "REQ", true, true),
        "INVIAFLUSSORENDI_RES" -> GdeConfiguration("INVIAFLUSSORENDI", "RES", true, true)
      ),
      Map(
        "m1" -> MetadataDict("m1", Some("1"), OffsetDateTime.now().minusDays(1), Some(OffsetDateTime.now().plusDays(1))),
        "m2" -> MetadataDict("m2", Some("2"), OffsetDateTime.now().minusDays(1), Some(OffsetDateTime.now().plusDays(1))),
        "m3" -> MetadataDict("m3", Some("3"), OffsetDateTime.now().minusDays(1), Some(OffsetDateTime.now().plusDays(1))),
        "METADATA1" -> MetadataDict("METADATA1", Some("3"), OffsetDateTime.now().minusDays(1), Some(OffsetDateTime.now().plusDays(1))),
        "METADATA2" -> MetadataDict("METADATA2", Some("3"), OffsetDateTime.now().minusDays(1), Some(OffsetDateTime.now().plusDays(1)))
      )
    )
  }

}
