microservice-chart: &microservice-chart
  namespace: "nodo"
  image:
    repository: ghcr.io/pagopa/pagopa-wisp-soap-converter
    tag: 0.2.7
  canaryDelivery:
    create: false
wispsoapconverter:
  !!merge <<: *microservice-chart
  nameOverride: ""
  fullnameOverride: ""
  terminationGracePeriodSeconds: 140
  livenessProbe:
    httpGet:
      path: /alive
      port: 8558
    initialDelaySeconds: 60
    failureThreshold: 10
    periodSeconds: 5
  readinessProbe:
    httpGet:
      path: /ready
      port: 8558
    initialDelaySeconds: 60
    failureThreshold: 10
    periodSeconds: 5
  tmpVolumeMount:
    create: true
  resources:
    requests:
      memory: "512M"
      cpu: "512m"
    limits:
      memory: "2Gi"
      cpu: "1024m"
  autoscaling:
    enable: true
    triggers:
      - type: cpu
        metricType: Utilization
        metadata:
          value: "70"
      - type: memory
        metricType: Utilization
        metadata:
          value: "80"
    advanced:
      horizontalPodAutoscalerConfig:
        behavior:
          scaleDown:
            stabilizationWindowSeconds: 300
            policies:
              - type: Pods
                value: 1
                periodSeconds: 20
          scaleUp:
            stabilizationWindowSeconds: 0
            policies:
              - type: Percent
                value: 100
                periodSeconds: 20
  envConfig:
    SERVICE_IDENTIFIER: "WSC001"
    AZURE_INSIGHTS_ENABLED: "true"
    APPLICATIONINSIGHTS_ROLE_NAME: "wispsoapconverter"
    MANAGEMENT_HTTP_PORT: "8558"
    MANAGEMENT_HTTP_BIND_HOST: "0.0.0.0"
    MANAGEMENT_HTTP_BIND_PORT: "8558"
    SERVICE_HTTP_PORT: "8080"
    SERVICE_HTTP_BIND_HOST: "0.0.0.0"
    SERVICE_HTTP_BIND_PORT: "8080"
    PROMETHEUS_HOST: "0.0.0.0"
    PROMETHEUS_PORT: "9091"
    MICROMETER_HOST: "0.0.0.0"
    MICROMETER_PORT: "9092"
    TZ: "Europe/Rome"
    AKKA_SYSTEM_NAME: "wispsoapconverter"
    JAVA_OPTS: >-
      -Dlogback.configurationFile=/mnt/file-config/logback.xml -Dconfig.app=/mnt/file-config/config-app.conf -Duser.language=it  -Duser.country=IT -Duser.timezone=Europe/Rome -Dfile.encoding=UTF-8 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3000 -Dcom.sun.management.jmxremote.rmi.port=3000 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
    INSTANCE: PROD
    API_CONFIG_CACHE_URL: "https://api.platform.pagopa.it/api-config-cache/p/v1/cache"
    AZURE_COSMOS_ENDPOINT: "https://pagopa-p-weu-nodo-wispconv-cosmos-account.documents.azure.com:443/"
    AZURE_STORAGE_BLOB_NAME: "payloads"
    AZURE_STORAGE_TABLE_NAME: "events"
    AZURE_COSMOS_DB_NAME: "wispconverter"
    AZURE_COSMOS_TABLE_NAME_DATA: "data"
    AZURE_COSMOS_TABLE_NAME_EVENTS: "re"
    ADAPTER_ECOMMERCE_URL: "https://wisp2.pagopa.it/wisp-converter/redirect/api/v1/payments?sessionId="
    RE_XML_LOG_ACTIVE: "false"
    RE_JSON_LOG_ACTIVE: "true"
  secretProvider:
    create: true
    envSecrets:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "azure-insight-connection-string"
      API_CONFIG_CACHE_SUBSCRIPTION_KEY: "api-config-cache-subscription-key-string"
      AZURE_COSMOS_KEY: "cosmosdb-wisp-converter-account-key"
      AZURE_STORAGE_CONNECTION_STRING: "wisp-converter-re-sa-connection-string-key"
    keyvault:
      name: "pagopa-p-nodo-kv"
      tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  envFieldRef:
    MANAGEMENT_HTTP_HOST: "status.podIP"
    SERVICE_HTTP_HOST: "status.podIP"
    MICROMETER_HOSTNAME: "metadata.name"
    NAMESPACE: "metadata.namespace"
    CINNAMON_HOST: "metadata.name"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
    APP_NAME: "metadata.labels['app.kubernetes.io/name']"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #micrometer
        targetPort: 9092
        path: /
      - interval: 10s #cinnamon
        targetPort: 9091
        path: /metrics
  ports:
    - 8080 #http
    - 8558 #akka-management
    - 9091 #cinnamon
    - 9092 #micrometer
    - 3000 #jmx debug port
  service:
    type: ClusterIP
    ports:
      - 8080 #http
      - 9091 #cinnamon
      - 9092 #micrometer
  ingress:
    create: true
    host: "weuprod.nodo.internal.dev.platform.pagopa.it"
    path: /wisp-soap-converter(/|$)(.*)
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "130"
    proxyBodySize: 100m
