ALTER TABLE "${schema}"."BINARY_FILE" ADD CONSTRAINT "BINARY_FILE_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."BINARY_FILE_PK" ON "${schema}"."BINARY_FILE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."RENDICONTAZIONE" ADD CONSTRAINT "RENDICONTAZIONE_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."RENDICONTAZIONE_PK" ON "${schema}"."RENDICONTAZIONE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."SCHEDULER_TRACE" ADD CONSTRAINT "SCHEDULER_TRACE" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."SCHEDULER_TRACE" ON "${schema}"."SCHEDULER_TRACE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."RENDICONTAZIONE_SFTP_SEND_QUEUE" ADD CONSTRAINT "RENDICONTAZIONE_SFTP_SEND_QUEUE_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."RENDICONTAZIONE_SFTP_SEND_QUEUE_PK" ON "${schema}"."RENDICONTAZIONE_SFTP_SEND_QUEUE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."RENDICONTAZIONE_SFTP_SEND_QUEUE" ADD CONSTRAINT "RENDICONTAZIONE_SFTP_SEND_QUEUE_CK_STATUS" CHECK ("STATUS"='NEW' OR "STATUS"='RECEIVED') DISABLE;
ALTER TABLE "${schema}"."RENDICONTAZIONE_SFTP_RECEIVE_QUEUE" ADD CONSTRAINT "RENDICONTAZIONE_SFTP_RECEIVE_QUEUE_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."RENDICONTAZIONE_SFTP_RECEIVE_QUEUE_PK" ON "${schema}"."RENDICONTAZIONE_SFTP_RECEIVE_QUEUE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."RENDICONTAZIONE_SFTP_RECEIVE_QUEUE" ADD CONSTRAINT "RENDICONTAZIONE_SFTP_RECEIVE_QUEUE_CK_STATUS" CHECK (STATUS IN ('NEW', 'RECEIVED')) DISABLE;
ALTER TABLE "${schema}"."SCHEDULER_FIRE_CHECK" ADD CONSTRAINT "SCHEDULER_FIRE_CHECK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."SCHEDULER_FIRE_CHECK" ON "${schema}"."SCHEDULER_FIRE_CHECK" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;