CREATE INDEX "${schema}"."REND_ELENCO_FLUSSI" ON "${schema}"."RENDICONTAZIONE" ("STATO", "DATA_ORA_FLUSSO", "DOMINIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" PARALLEL 1 ;

  ALTER INDEX "${schema}"."REND_ELENCO_FLUSSI" NOPARALLEL;
CREATE INDEX "${schema}"."RENDICONTAZIONE_IDX1" ON "${schema}"."RENDICONTAZIONE" ("STATO", "ID_FLUSSO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" PARALLEL 1 ;

  ALTER INDEX "${schema}"."RENDICONTAZIONE_IDX1" NOPARALLEL;
CREATE INDEX "${schema}"."SCHEDULER_FIRE_CHECK_JOB_NAME_EXTRA_KEY_IDX" ON "${schema}"."SCHEDULER_FIRE_CHECK" ("JOB_NAME", "EXTRA_KEY")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" PARALLEL 1 ;

  ALTER INDEX "${schema}"."SCHEDULER_FIRE_CHECK_JOB_NAME_EXTRA_KEY_IDX" NOPARALLEL;
CREATE INDEX "${schema}"."SCHEDULER_TRACE_ID_SESSIONE_IDX" ON "${schema}"."SCHEDULER_TRACE" ("ID_SESSIONE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" PARALLEL 1 ;

  ALTER INDEX "${schema}"."SCHEDULER_TRACE_ID_SESSIONE_IDX" NOPARALLEL;